stiftungswo/better-izivi

api/app/controllers/v1/service_specifications_controller.rb, api/app/models/service_specification.rb, api/db/migrate/20190429132515_create_service_specifications.rb, api/db/schema.rb, api/spec/requests/v1/service_specifications_controller_spec.rb
=> Improvements

api/app/controllers/concerns/v1/admin_authorizable.rb, api/app/controllers/v1/api_controller.rb, api/app/controllers/v1/payments_controller.rb, api/spec/requests/v1/payments_controller_spec.rb
=> Admin protect PAIN generation

api/app/controllers/v1/users_controller.rb, api/app/models/user.rb, api/app/views/v1/users/index.json.jbuilder, api/config/routes.rb, api/debugging/requests/users/index.http, api/spec/models/user_spec.rb, api/spec/requests/v1/users_controller_spec.rb
Added `v1_users GET /v1/users(.:format) v1/users#index {:format=>:json}`
=> Implement /users Route

api/app/controllers/v1/service_specifications_controller.rb, api/app/controllers/v1/services_controller.rb, api/app/models/service.rb, api/app/models/service_specification.rb, api/app/views/v1/service_specifications/_service_specification.json.jbuilder, api/app/views/v1/services/index.json.jbuilder, api/db/migrate/20190627105124_add_identification_number_to_service_specification.rb, api/db/schema.rb, api/db/seed_data/service_specifications.rb, api/spec/factories/service_specifications.rb, api/spec/models/service_spec.rb, api/spec/models/service_specification_spec.rb, api/spec/requests/v1/services_controller_spec.rb, frontend/src/form/entitiySelect/ServiceSpecificationSelect.tsx, frontend/src/stores/serviceSpecificationStore.ts, frontend/src/stores/serviceStore.ts, frontend/src/types.ts, frontend/src/views/service_overview/ServiceOverview.tsx, frontend/src/views/service_specification/ServiceSpecificationsOverview.tsx, frontend/src/views/service_specification/serviceSpecificationSchema.ts, frontend/src/views/users/service_subform/ServiceOverviewTable.tsx
Implement service overview in frontend and adapted type of /services endpoint
=> Frontend: Adapt Services Overview

frontend/src/stores/apiStore.ts
=> Fix logout bug

frontend/src/views/PhoneList.tsx
=> Adapt phone list URL

api/app/models/service.rb, api/app/services/normal_service_calculator.rb, api/app/services/service_calculator.rb, api/app/views/v1/services/_service.json.jbuilder, api/spec/models/service_spec.rb, api/spec/requests/v1/services_controller_spec.rb, api/spec/services/normal_service_calculator_spec.rb, api/spec/services/service_calculator_spec.rb
=> Rename eligible_personal_vacation_days to eligible_paid_vacation_days

frontend/src/layout/IziviContent.tsx, frontend/src/views/service_overview/ServiceOverview.tsx, frontend/src/views/service_specification/ServiceSpecificationsOverview.tsx
Looks now like this:
But is still wide in planning:
=> Adapt layout to something not that enormously wide :)

api/spec/models/holiday_spec.rb, api/spec/models/service_spec.rb, api/spec/models/user_spec.rb, api/spec/support/json_response_spec_helper.rb
This reduces the spec execution time by -1.68s 🎉 🥳
=> Some performance improvements to tests

api/app/views/v1/expense_sheets/index.json.jbuilder, api/spec/requests/v1/expense_sheets_controller_spec.rb, frontend/src/types.ts, frontend/src/views/expense_sheets/ExpenseSheetOverview.tsx, frontend/src/views/users/ExpenseSheetSubform.tsx
=> Fix Expense Sheet Overview

frontend/src/App.tsx, frontend/src/views/payments/detail/PaymentDetail.tsx, frontend/src/views/payments/detail/paymentDetailStyles.ts
Now has fancy animation on cancel
=> Add fancy animation

frontend/src/stores/expenseSheetStore.ts
=> Refactor expense sheet store

frontend/src/views/users/service_modal/ServiceModal.tsx, frontend/src/views/users/service_modal/ServiceModalForm.tsx
=> Service Form Ending only editable for Admin

api/app/controllers/v1/phone_list_controller.rb
=> User correct service scope

api/app/controllers/v1/service_calculator_controller.rb, api/app/models/service.rb, api/app/services/normal_service_calculator.rb, api/app/services/service_calculator.rb, api/spec/requests/v1/service_calculator_controller_spec.rb, api/spec/services/normal_service_calculator_spec.rb, api/spec/services/service_calculator_spec.rb
=> Update specs and check for last service

api/app/models/concerns/legacy_password_authenticatable.rb, api/app/models/user.rb, api/spec/models/user_spec.rb
=> Workaround for legacy passwords

api/.env.example, api/app/helpers/devise/reset_password_instructions_helper.rb, api/app/views/devise/mailer/reset_password_instructions.html.erb, api/config/initializers/devise.rb, api/debugging/requests/authentication/reset_password.http, api/spec/helpers/devise/reset_password_instructions_helper_spec.rb, frontend/src/App.tsx, frontend/src/stores/apiStore.ts, frontend/src/views/ChangeForgottenPassword.tsx, frontend/src/views/ForgotPassword.tsx, frontend/src/views/Login.tsx
Implemented password reset form in frontend
Resolves #205
=> Password Reset

api/app/controllers/v1/users_controller.rb, api/app/models/concerns/legacy_password_authenticatable.rb, api/app/models/user.rb, api/app/services/pdfs/service_agreement/form_filler.rb, api/app/views/devise/mailer/reset_password_instructions.html.erb, api/app/views/shared/users/_user.json.jbuilder, api/config/initializers/devise.rb, api/lib/tasks/v1_migration.rake, api/spec/models/user_spec.rb, api/spec/requests/v1/users_controller_spec.rb, frontend/yarn.lock
=> Fix password reset

api/app/models/expense_sheet.rb, api/config/locales/de.yml, api/config/locales/en.yml, api/config/locales/fr.yml, api/spec/factories/expense_sheets.rb, api/spec/factories/services.rb, api/spec/models/expense_sheet_spec.rb, api/spec/requests/v1/expense_sheets_controller_spec.rb, api/spec/requests/v1/payments_controller_spec.rb, api/spec/requests/v1/users_controller_spec.rb, api/spec/services/pain_generation_service_spec.rb
=> Prevent expense sheet from invalid updates

api/app/controllers/v1/users_controller.rb, api/app/models/service.rb, api/app/models/user.rb, api/app/views/shared/users/_user.json.jbuilder, api/app/views/v1/users/index.json.jbuilder, api/spec/models/service_spec.rb, api/spec/models/user_spec.rb, api/spec/requests/v1/users_controller_spec.rb, frontend/src/stores/userStore.ts, frontend/src/types.ts, frontend/src/utilities/helpers.ts, frontend/src/views/users/UserOverview.tsx
=> Users List Performance Optimizations

frontend/src/App.tsx, frontend/src/layout/Navigation.tsx, frontend/src/stores/domainStore.ts, frontend/src/stores/serviceSpecificationStore.ts, frontend/src/types.ts, frontend/src/views/holidays/HolidayOverview.tsx, frontend/src/views/service_specification/ServiceSpecificationsOverview.tsx, frontend/src/views/service_specification/serviceSpecificationSchema.ts
=> Fix service specification crud

frontend/src/layout/OverviewTable.tsx
=> Added total amount to payments

frontend/src/views/service_overview/ServiceOverview.tsx
=> switched to two years in future

frontend/src/layout/IziviContent.tsx
=> Printable payments layout

frontend/src/stores/apiStore.ts, frontend/src/views/Login.tsx
remove the authorization token if it is expires so we don't have to retry a login multiple times even if the input was correct.
this closes #314
=> remove the authorization token if it is expired

api/app/models/expense_sheet.rb, api/app/views/v1/expense_sheets/_expense_sheet.json.jbuilder, api/app/views/v1/services/_service.json.jbuilder, api/spec/requests/v1/expense_sheets_controller_spec.rb, api/spec/requests/v1/expenses_overview_controller_spec.rb, frontend/cypress/integration/expense_sheet_spec.js, frontend/src/form/DeleteButton.tsx, frontend/src/types.ts, frontend/src/views/expense_sheets/expense_sheet_form/ExpenseSheetFormButtons.tsx, frontend/src/views/users/service_modal/ServiceModal.tsx, frontend/src/views/users/service_subform/ServiceOverviewTable.tsx, frontend/src/views/users/service_subform/ServiceSubform.tsx
=> auto reload content instead of refreshing the page and restrict expense sheet modification

api/app/services/pdfs/phone_list_service.rb, api/spec/services/pdfs/phone_list_service_spec.rb
=> fix order of firstname lastname on phonelist pdf #332

frontend/src/form/FormikSubmitDetector.tsx, frontend/src/stores/apiStore.ts, frontend/src/stores/mainStore.ts
Fix for #361 and a false error message in the profile form. The error message there was also always in german.
=> Language support improvements

frontend/src/form/FormikSubmitDetector.tsx, frontend/src/stores/apiStore.ts, frontend/src/stores/mainStore.ts
Axios 0.21.1 does not support axios.defaults.params, therefore the code from #366 does also not work
=> Revert "Language support improvements"

frontend/src/stores/apiStore.ts, frontend/src/stores/mainStore.ts
=> send local to backend

frontend/src/form/FormView.tsx, frontend/src/form/FormikSubmitDetector.tsx, frontend/src/stores/apiStore.ts, frontend/src/stores/mainStore.ts
=> Language support for french improved and other minor bug fixes

api/app/services/subscribe_to_newsletter.rb
=> variable net could not be found before

api/app/controllers/v1/expense_sheets_controller.rb, api/app/controllers/v1/users_controller.rb, api/app/views/v1/expense_sheets/sum.json.jbuilder, api/config/routes.rb, api/debugging/requests/expense_sheets/sum.http, frontend/src/layout/Overview.tsx, frontend/src/layout/OverviewTable.tsx, frontend/src/locales/messages.de.json, frontend/src/locales/messages.en.json, frontend/src/locales/messages.fr.json, frontend/src/stores/expenseSheetStore.ts, frontend/src/stores/userStore.ts, frontend/src/types.ts, frontend/src/views/expense_sheets/ExpenseSheetOverview.tsx, frontend/src/views/users/UserOverview.tsx
introduce pagination for users page and expense sheets page
=> 238 pagination users expense sheets

frontend/src/App.tsx, frontend/src/layout/IziviLayout.tsx, frontend/src/layout/NavbarBrand.tsx, frontend/src/layout/Navigation.tsx, frontend/src/utilities/AppMode.ts
=> Differentiate UI

api/app/controllers/v1/payments_list_controller.rb, api/app/services/pdfs/payments_list_service.rb, api/config/locales/de.yml, api/config/locales/en.yml, api/config/locales/fr.yml, api/spec/requests/v1/payments_list_controller_spec.rb, frontend/src/views/payments/detail/PaymentDetail.tsx, frontend/src/views/payments/tables/ExpenseSheetsReadyForPaymentTable.tsx
=> Add pdf for payments that are archived and being processed

api/app/services/pdfs/service_agreement/form_filler.rb, api/spec/rails_helper.rb, api/spec/requests/v1/expense_sheets_controller_spec.rb, api/spec/requests/v1/expenses_overview_controller_spec.rb, docker-compose.yml
Co-authored-by: Florentin @floerb
=> Mixed small bugfixes to (hopefully) get rid off the random failure

api/app/controllers/concerns/devise_user_params_registrable.rb, api/app/views/shared/users/_user.json.jbuilder, api/db/migrate/20220914055352_add_photographs_accepted_to_user.rb, api/db/schema.rb, frontend/cypress/server/initial_db.json, frontend/src/locales/messages.de.json, frontend/src/locales/messages.en.json, frontend/src/locales/messages.fr.json, frontend/src/types.ts, frontend/src/views/users/UserForm.tsx
=> Photo Checkbox

frontend/src/form/CheckboxField.tsx, frontend/src/locales/messages.de.json, frontend/src/views/users/service_modal/ServiceModal.tsx, frontend/src/views/users/service_modal/ServiceModalForm.tsx
=> Disallow service to be changed to probation retroactivly

frontend/cypress/integration/register_spec.js, frontend/src/form/formik.tsx, frontend/src/locales/messages.de.json, frontend/src/locales/messages.fr.json, frontend/src/stores/apiStore.ts, frontend/src/types.ts, frontend/src/views/register/RegisterForm.tsx, frontend/src/views/register/RegisterFormInner.tsx, frontend/src/views/register/pages/PersonalDetailsPage.tsx, frontend/src/views/users/UserForm.tsx
feat: add selectbox for foto permission to force new users to select an option.
=> Registration Process Selection #492
